"""Ticket definitions for docs/PLAN.md. Consumed by scripts/file_issues.py.

Each ticket: (id, title, labels, body). `id` is the plan number (e.g. "1.3").
In bodies, refer to other tickets as [1.3]; the filing script rewrites those
to real issue links after creation.
"""

MILESTONES = [
    ("Phase 0: Workstation and repo foundations", "No hardware needed. Nix on WSL, flake skeleton, CI, sops bootstrap, ADRs, task runner. Do in order 0.1 to 0.7."),
    ("Phase 1: Bare-metal install and base OS", "disko layout, base module, network, Tailscale, nixos-anywhere install, host age key, reinstall runbook."),
    ("Phase 2: GitOps, updates, rollback", "comin pull deploys, weekly flake.lock PRs, maintenance-window reboots, rollback drill, failure notifications, README."),
    ("Phase 3: Container platform, observability, backups", "Docker, reusable compose-stack module, data layout, Prometheus/Grafana, restic to nasberrypi, alerting."),
    ("Phase 4: Game servers", "Minecraft, Palworld, Satisfactory stacks, port forwards, maintenance hooks, resource policy, new-server template."),
    ("Phase 5: Local LLMs", "Ollama on CPU, Open WebUI, model storage budget, Intel iGPU and NPU trials."),
    ("Phase 6: Development environment", "home-manager, Shopify dev shells, sops-backed tokens, VS Code Remote, scheduled scripts."),
    ("Phase 7: Hardening, DR, write-up", "DR drill, security review, SMART/scrub, Secure Boot (stretch), CV write-up."),
    ("Phase 8: Kubernetes (stretch)", "K3s ADR, single-node install, migrate one stack, go/no-go."),
]

LABELS = [
    ("phase:0", "c5def5", "Phase 0 workstation and repo foundations"), ("phase:1", "c5def5", "Phase 1 bare-metal install"),
    ("phase:2", "c5def5", "Phase 2 GitOps and updates"), ("phase:3", "c5def5", "Phase 3 containers, observability, backups"),
    ("phase:4", "c5def5", "Phase 4 game servers"), ("phase:5", "c5def5", "Phase 5 local LLMs"), ("phase:6", "c5def5", "Phase 6 dev environment"),
    ("phase:7", "c5def5", "Phase 7 hardening and DR"), ("phase:8", "c5def5", "Phase 8 Kubernetes"),
    ("area:nix", "5319e7", "Nix flake and NixOS modules"), ("area:ci", "0e8a16", "GitHub Actions"), ("area:install", "d93f0b", "Bare-metal install and hardware"),
    ("area:network", "1d76db", "Networking, Tailscale, firewall"), ("area:containers", "fbca04", "Docker and compose stacks"), ("area:games", "e99695", "Game servers"),
    ("area:llm", "bfd4f2", "Local LLM hosting"), ("area:dev", "c2e0c6", "Development environment"), ("area:backup", "f9d0c4", "Backups and restore"),
    ("area:security", "b60205", "Security hardening"), ("area:docs", "0052cc", "Documentation, ADRs, runbooks"), ("area:observability", "006b75", "Monitoring and alerting"),
    ("stretch", "ededed", "Optional, do after the core is stable"),
]


def t(id_, title, labels, goal, tasks, ac, deps="Nothing."):
    body = f"## Goal\n{goal}\n\n## Tasks\n" + "\n".join(f"- [ ] {x}" for x in tasks)
    body += "\n\n## Acceptance criteria\n" + "\n".join(f"- {x}" for x in ac)
    body += f"\n\n## Depends on\n{deps}\n"
    return (id_, f"{id_} {title}", [f"phase:{id_.split('.')[0]}"] + labels, body)


TICKETS = [
# ---------------- Phase 0 ----------------
t("0.1", "Install Nix and direnv on the WSL workstation", ["area:nix"],
  "Get a flakes-enabled Nix on the Ubuntu 24.04 WSL workstation so every later ticket can be built and checked locally before it reaches the server.",
  ["Install Nix with the Determinate installer (flakes and nix-command on by default)",
   "Install `direnv` and `nix-direnv`, hook into the shell",
   "Confirm `nix.conf` has `experimental-features = nix-command flakes`",
   "Record the install method and any WSL quirks in `docs/runbooks/workstation.md`"],
  ["`nix flake --version` prints a version", "`nix run nixpkgs#hello` prints Hello, world!", "A test `.envrc` with `use flake` loads via direnv"]),
t("0.2", "Repo hygiene: gitignore, editorconfig, CODEOWNERS, issue templates", ["area:docs"],
  "Make the public repo tidy and consistent before code lands. (Repo, README, license and PLAN.md already exist.)",
  ["Add `.gitignore` (result symlinks, `.direnv/`, `*.qcow2`, `.pre-commit-cache`)",
   "Add `.editorconfig` (2-space nix/yaml, LF, trailing newline)",
   "Add `.github/ISSUE_TEMPLATE/ticket.md` matching the Goal/Tasks/AC/Depends-on layout used here",
   "Add `.github/pull_request_template.md` with a checklist: `nix flake check` passed locally, ADR updated if a decision changed"],
  ["All four files on `main`", "Opening a new issue offers the ticket template"]),
t("0.3", "Flake skeleton with a stub nixosConfigurations.nuc", ["area:nix"],
  "Create the flake that everything else hangs off, with a system that evaluates and builds even before hardware exists.",
  ["`flake.nix` with inputs: `nixpkgs` (nixos-26.05), `disko`, `sops-nix`, `home-manager` (release-26.05), `comin`",
   "`hosts/nuc/default.nix` importing `modules/base`, with a placeholder `hardware-configuration.nix` and `fileSystems` so the closure builds",
   "`modules/base/default.nix` with `system.stateVersion = \"26.05\"`, hostname `nuc`",
   "`formatter` = nixfmt (or alejandra) and a `checks` output that builds the toplevel",
   "`flake.lock` committed"],
  ["`nix flake check` passes locally", "`nix build .#nixosConfigurations.nuc.config.system.build.toplevel` succeeds"],
  "[0.1]"),
t("0.4", "GitHub Actions CI: flake check, build closure, format check", ["area:ci"],
  "Every pull request and push to `main` is validated on GitHub-hosted runners so `main` is always deployable.",
  ["`.github/workflows/ci.yml` triggered on `pull_request` and `push` to `main`",
   "Use `DeterminateSystems/nix-installer-action` and `DeterminateSystems/magic-nix-cache-action`",
   "Steps: `nix flake check`, `nix build .#nixosConfigurations.nuc.config.system.build.toplevel`, `nix fmt -- --check .`",
   "Add a status badge to README",
   "Enable branch protection on `main`: require the CI check, no force pushes"],
  ["A pull request shows a green CI check", "A pull request with a syntax error in a `.nix` file shows red"],
  "[0.3]"),
t("0.5", "Secrets bootstrap with sops-nix and age", ["area:security", "area:nix"],
  "Establish encrypted secrets in the public repo before any real secret is needed. See ADR 0004.",
  ["Generate a workstation age key (`age-keygen`), store at `~/.config/sops/age/keys.txt`, back it up to the NAS",
   "Create `.sops.yaml` with the workstation key and a placeholder host key entry",
   "Add `secrets/test.yaml` containing one dummy secret, encrypted",
   "Wire `sops-nix` into `modules/base` with `sops.defaultSopsFile` and `sops.secrets.test`",
   "Confirm decryption in a local NixOS VM (`nixos-rebuild build-vm`) using the workstation key"],
  ["`sops -d secrets/test.yaml` prints plaintext on the workstation", "Inside the VM, `/run/secrets/test` has the expected content", "`git log -p` and a secret scan show only ciphertext"],
  "[0.3]"),
t("0.6", "Architecture decision records for the six locked decisions", ["area:docs"],
  "ADRs 0001 to 0005 already exist. Review them and add ADR 0006 for the container runtime choice.",
  ["Re-read ADRs 0001-0005, fix anything that no longer matches the plan",
   "Write `docs/adr/0006-docker-vs-podman.md`: Docker (default) vs Podman with docker compat. Decide before [3.1]",
   "Add `docs/adr/README.md` index with a one-line summary per ADR"],
  ["Six ADRs, each with Context, Decision, Consequences", "Index lists all six"]),
t("0.7", "Task runner: just targets for fmt, check, build, vm, deploy", ["area:nix"],
  "Give the repo the same one-word ergonomics the NAS project had with `pixi run`, using `just` inside a dev shell.",
  ["Add `devShells.default` with `just`, `sops`, `age`, `nixfmt`, `nixos-anywhere`, `nixos-rebuild`",
   "`justfile` targets: `fmt`, `check`, `build`, `vm` (builds and runs a QEMU VM of `nuc`), `deploy` (manual `nixos-rebuild switch --flake .#nuc --target-host ops@nuc --use-remote-sudo`), `secrets-edit <file>`",
   "`.envrc` with `use flake` so the dev shell loads automatically",
   "Document the targets in README"],
  ["`just vm` boots the config and reaches a login prompt", "`just check` equals what CI runs"],
  "[0.3], [0.5]"),

# ---------------- Phase 1 ----------------
t("1.1", "Hardware prep and BIOS settings", ["area:install"],
  "Physically assemble the NUC and set BIOS options so it behaves as a headless server.",
  ["Seat both DDR5 SO-DIMMs (96 GB) and the 1 TB NVMe in the primary M.2 slot",
   "BIOS: restore power on AC loss = on, boot order USB first then NVMe, Secure Boot off (see [7.4]), VT-x and VT-d on, fan curve sensible for 24/7",
   "Record BIOS version, RAM part numbers, NVMe model and the `eno1` MAC in `docs/runbooks/hardware.md`",
   "Boot the NixOS 26.05 minimal ISO from USB and confirm `lspci` shows the Xe3 iGPU and two Intel 2.5GbE NICs, `free -g` shows about 94 GB"],
  ["Runbook checklist complete", "Live ISO boots, both NICs get DHCP leases"]),
t("1.2", "disko layout: GPT, ESP, btrfs subvolumes, swap", ["area:install", "area:nix"],
  "Declare the disk so a reinstall is bit-for-bit repeatable and data lives on snapshot-able subvolumes.",
  ["`hosts/nuc/disko.nix`: GPT, 1 GB ESP at `/boot`, rest btrfs",
   "Subvolumes: `@root` (/), `@nix` (/nix, noatime), `@home`, `@srv` (/srv, holds `/srv/data/<stack>`), `@docker` (/var/lib/docker), `@snapshots` (/.snapshots), `@swap`",
   "16 GB swapfile on `@swap` with `nodatacow`, or `zramSwap` if preferred; record the choice",
   "Compression `zstd:1` on data subvolumes, none on `@docker`",
   "Note the empty second M.2 slot as the future data disk in `docs/runbooks/hardware.md`"],
  ["`nix build .#nixosConfigurations.nuc.config.system.build.diskoScript` succeeds", "Layout reviewed against the plan"],
  "[0.3]"),
t("1.3", "Base module: users, sshd, nix settings, kernel, GC", ["area:nix", "area:security"],
  "The minimum a fresh install needs to be safely reachable and self-maintaining.",
  ["User `ops`: `wheel`, `docker` (later), SSH public key from the workstation, no password",
   "`security.sudo.wheelNeedsPassword = false` (single-admin box; revisit in [7.2])",
   "`services.openssh`: `PasswordAuthentication = false`, `PermitRootLogin = \"no\"`, ed25519 host key only",
   "`nix.settings`: `experimental-features`, `trusted-users = [\"ops\"]`, `auto-optimise-store`; `nix.gc` weekly keep 14 days",
   "`boot.kernelPackages = pkgs.linuxPackages_latest`; `hardware.cpu.intel.updateMicrocode = true`; `hardware.enableRedistributableFirmware = true`",
   "`boot.loader.systemd-boot` with `configurationLimit = 10`",
   "Timezone Europe/London (adjust), locale, `programs.git`, `tmux` with the config ported from ansible-nasberrypi"],
  ["`just vm` boots, `ssh ops@localhost -p <vm port>` works with the key and fails with a password", "`nixos-version` in the VM shows 26.05"],
  "[0.3], [1.2]"),
t("1.4", "LAN networking: DHCP reservation, hostname, firewall default deny", ["area:network"],
  "Give the server a stable LAN identity and a closed firewall before it goes online.",
  ["Router: DHCP reservation for the `eno1` MAC, name `nuc.home.arpa`",
   "`networking.useDHCP` on `eno1` only; second NIC left down and documented",
   "`networking.firewall.enable = true`, no open ports yet; SSH allowed only on the Tailscale interface after [1.5]. Temporarily allow 22 on LAN until Tailscale is confirmed",
   "`networking.nftables.enable = true`"],
  ["From the LAN, `ping nuc.home.arpa` resolves to the reserved IP", "`nmap` from the LAN shows only 22 (until [1.5] closes it)"],
  "[1.3]"),
t("1.5", "Tailscale module with sops auth key", ["area:network", "area:security"],
  "All admin access goes over the tailnet. See ADR 0005.",
  ["`services.tailscale.enable`, `useRoutingFeatures = \"client\"`, `authKeyFile = config.sops.secrets.tailscale-authkey.path` (reusable, pre-authorized key from the Tailscale admin console)",
   "Enable MagicDNS and Tailscale SSH or keep sshd; either way sshd listens on the tailnet interface",
   "`networking.firewall.trustedInterfaces = [\"tailscale0\"]`; remove the temporary LAN port 22 rule",
   "Join the workstation (WSL) and phone to the tailnet"],
  ["`ssh ops@nuc` from WSL works over Tailscale with the workstation on a different network (phone hotspot)", "`nmap` from the LAN shows no open ports"],
  "[1.3], [0.5]"),
t("1.6", "Install with nixos-anywhere from the live USB", ["area:install"],
  "First real install. After this the machine only ever changes through the repo.",
  ["Boot the NixOS minimal ISO, set a root password, note the DHCP IP",
   "From WSL: `nixos-anywhere --flake .#nuc --target-host root@<ip>` (uses disko from [1.2])",
   "Post-install: `nixos-generate-config --show-hardware-config` on the host, commit the real `hosts/nuc/hardware-configuration.nix`, push, rebuild",
   "Check `dmesg` for NIC (`igc`) and GPU (`xe`) errors; check `/dev/dri` exists"],
  ["Reboots into NixOS 26.05 without USB", "`ssh ops@nuc.home.arpa` works", "`lspci -k` shows `xe` bound to the iGPU and `igc` to both NICs", "No firmware-missing errors in `dmesg`"],
  "[1.1], [1.2], [1.3], [1.4]"),
t("1.7", "Host age key and secret re-encryption", ["area:security"],
  "Let the server decrypt its own secrets from its SSH host key so no key material is copied by hand.",
  ["On the host: `ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub` and add the result to `.sops.yaml` as the `nuc` host",
   "`sops updatekeys secrets/*.yaml`, commit, push",
   "Verify `sops-nix` decrypts on the host at activation",
   "Add the Tailscale auth key ([1.5]) as the first real secret"],
  ["`sudo cat /run/secrets/test` on nuc prints the plaintext", "Tailscale comes up on a fresh rebuild without manual `tailscale up`"],
  "[1.6], [0.5]"),
t("1.8", "Reinstall runbook and Phase 1 smoke tests", ["area:docs", "area:install"],
  "A wipe-and-reinstall must be a documented, under-one-hour procedure. This runbook is the DR baseline for [7.1].",
  ["`docs/runbooks/reinstall.md` covering [1.1] to [1.7] in order, with the exact commands",
   "Smoke test list: SSH over Tailscale, secrets decrypt, `nix flake check` on host, firewall closed on LAN, kernel is `linuxPackages_latest`",
   "Record time taken for the first install as the baseline"],
  ["Runbook reviewed and followed once end-to-end", "All smoke tests pass"],
  "[1.7]"),

# ---------------- Phase 2 ----------------
t("2.1", "comin pull-based deployment from main", ["area:ci", "area:nix"],
  "The server deploys itself from `main`. See ADR 0003.",
  ["Add the `comin` NixOS module; remote = this repo (public HTTPS, no token needed), branch `main`, poll about 60 s",
   "Consider `comin` GPG commit verification and document why enabled or not",
   "Remove any temporary manual-deploy habit; `just deploy` stays for emergencies",
   "Add `comin` status to the smoke tests"],
  ["Push a change to `users.motd`, see it on the host within 2 minutes without any SSH", "`systemctl status comin` healthy after reboot"],
  "[1.8], [0.4]"),
t("2.2", "Weekly flake.lock update pull requests", ["area:ci"],
  "Keep nixpkgs and inputs current with a reviewable PR each week, built by CI before merge.",
  ["`.github/workflows/update-flake-lock.yml` using `DeterminateSystems/update-flake-lock` on a weekly cron",
   "PRs labeled `dependencies`; CI from [0.4] runs on them",
   "After one month decide whether to enable auto-merge on green (record in ADR 0003 consequences)"],
  ["First automated PR merged and deployed via comin", "Decision on auto-merge recorded"],
  "[2.1]"),
t("2.3", "Safe update policy: reboot window and generation limits", ["area:nix", "area:docs"],
  "Updates that change the kernel must not reboot game servers mid-session.",
  ["`system.autoUpgrade.enable = false` (comin owns deploys)",
   "A systemd timer (e.g. Tue 04:00) that reboots only if `/run/current-system` kernel differs from `/run/booted-system`",
   "Hook point for a pre-reboot game broadcast, wired in [4.4]",
   "`docs/runbooks/updates.md`: how updates flow, how to pause comin, how to force a deploy"],
  ["A kernel bump waits for the window and reboots then", "A config-only change deploys immediately without reboot", "Runbook written"],
  "[2.1]"),
t("2.4", "Rollback drill: broken service, bootloader generation, git revert", ["area:nix", "area:docs"],
  "Prove both rollback paths before relying on them.",
  ["Merge a commit that breaks a systemd unit; confirm comin switches and the failure is visible but SSH survives",
   "Roll back via `git revert` and watch comin recover",
   "Merge a commit that breaks boot in the VM (e.g. bad `fileSystems`); confirm CI catches it; if it did not, boot the previous generation from systemd-boot",
   "Document both in `docs/runbooks/updates.md`"],
  ["Both recovery paths performed and timed", "CI catches the boot-breaking example"],
  "[2.3]"),
t("2.5", "Deployment and unit failure notifications", ["area:observability"],
  "Know within minutes when a deploy or a unit fails.",
  ["Pick ntfy (self-hosted or ntfy.sh topic) or a Discord webhook; store the URL in sops",
   "`systemd` `OnFailure=` handler unit that posts the failing unit name and last 20 journal lines",
   "Attach the handler to `comin`, backup, and each compose stack unit (via the [3.2] module)",
   "Add a comin success notification with commit hash (optional, can be noisy)"],
  ["Forcing a unit failure produces a notification on the phone", "Secret URL absent from the repo"],
  "[2.1], [1.7]"),
t("2.6", "README pipeline diagram and status badges", ["area:docs"],
  "Make the repo readable as portfolio evidence in one screen.",
  ["Mermaid diagram: PR to CI to merge to comin to nixos-rebuild; and the runtime layout (stacks, Tailscale, restic to NAS)",
   "Badges: CI, flake.lock update, license",
   "Short 'how to reproduce this' section pointing at `docs/runbooks/reinstall.md`"],
  ["README renders the diagram on GitHub", "A reader unfamiliar with Nix understands the flow"],
  "[2.1]"),

# ---------------- Phase 3 ----------------
t("3.1", "Docker module: data-root, log rotation, prune timer", ["area:containers"],
  "Container runtime configured declaratively. Decide Docker vs Podman in ADR 0006 first.",
  ["`virtualisation.docker.enable`, `daemon.settings`: `data-root = /var/lib/docker` (the `@docker` subvolume), `log-driver = journald` or json-file with rotation, `live-restore = true`",
   "`virtualisation.docker.autoPrune` weekly",
   "Add `ops` to the `docker` group",
   "`docker compose` plugin available (`pkgs.docker-compose`)"],
  ["`docker run --rm hello-world` as `ops`", "`docker info` shows the data-root on the btrfs subvolume", "ADR 0006 marked accepted"],
  "[1.8], [0.6]"),
t("3.2", "Reusable compose-stack NixOS module", ["area:containers", "area:nix"],
  "One module turns a compose file plus a sops env file into a systemd service, so every stack deploys through comin identically.",
  ["`modules/containers/compose-stack.nix` with options: `name`, `composeFile`, `envSecret` (sops path), `dataDir`, `resources` (MemoryMax, CPUWeight), `after` extras",
   "Generated unit: `After=docker.service network-online.target`, `ExecStart=docker compose --project-directory /etc/stacks/<name> up -d --remove-orphans`, `ExecStop=... down`, `RemainAfterExit=yes`",
   "Restart the unit when the compose file or env changes (`restartTriggers`)",
   "Compose files installed to `/etc/stacks/<name>/` via `environment.etc`",
   "`OnFailure=` wired to the [2.5] notifier",
   "`stacks/hello/docker-compose.yml` as the example stack"],
  ["`hello` stack deploys via comin and `systemctl status stack-hello` is active", "Editing the compose file and pushing restarts only that stack"],
  "[3.1]"),
t("3.3", "Data layout under /srv/data and ownership conventions", ["area:containers", "area:docs"],
  "Every stack's persistent state lives in one predictable place so backups and snapshots need no per-stack config.",
  ["`/srv/data/<stack>` per stack, created via `systemd.tmpfiles.rules` with a fixed uid/gid per stack",
   "Btrfs subvolume per stack under `@srv` (created by a small activation script or manually and documented)",
   "`docs/runbooks/data-layout.md`: path, owner, what is inside, what is excluded from backup"],
  ["`hello` stack and the first real stack use the layout", "Runbook written"],
  "[3.2]"),
t("3.4", "Observability: Prometheus, node-exporter, cAdvisor, Grafana", ["area:observability"],
  "See host and container health over Tailscale.",
  ["`services.prometheus` + `exporters.node` as NixOS modules (not containers) so they survive Docker issues",
   "`stacks/obs/docker-compose.yml`: Grafana + cAdvisor; Grafana bound to the Tailscale IP only, admin password from sops",
   "Provision Grafana datasource and dashboards from files in the repo (node exporter full, cAdvisor)",
   "Placeholder per-game dashboards for [4.x] (player count via exporters where images expose them)"],
  ["`http://nuc:3000` over Tailscale shows a populated host dashboard", "Grafana unreachable from LAN and WAN"],
  "[3.2], [3.3]"),
t("3.5", "restic backups to nasberrypi over SFTP", ["area:backup"],
  "Nightly, verified, alerting backups of everything under /srv/data to the existing NAS.",
  ["On nasberrypi: `/tank/backups/nuc` owned by `nasops`; add the nuc host key to `nasops`' `authorized_keys` (restrict to sftp if possible)",
   "`services.restic.backups.nas`: repository `sftp:nasops@nasberrypi.home.arpa:/tank/backups/nuc`, `passwordFile` from sops, paths `/srv/data`, exclude caches and model blobs (see [5.3])",
   "Pre-backup: btrfs snapshot of `@srv` into `@snapshots`, back up the snapshot, delete after",
   "Retention `--keep-daily 7 --keep-weekly 4 --keep-monthly 6`; `restic check` weekly via a second timer",
   "`OnFailure=` to the [2.5] notifier"],
  ["First backup completes; `restic snapshots` lists it", "Restore one file into `/tmp` and diff it", "Forcing a failure notifies"],
  "[3.3], [2.5]"),
t("3.6", "Alert rules: disk, backup age, failed units", ["area:observability"],
  "Turn dashboards into pages for the few things that matter.",
  ["Prometheus rules: root or `/srv` > 85 percent, `node_systemd_unit_state{state=\"failed\"} > 0`, restic last-success age > 36 h (expose via a textfile collector or `restic-exporter`)",
   "Alertmanager (NixOS module) or Grafana alerting to the [2.5] channel",
   "Test each rule by forcing the condition"],
  ["Three rules present and each fired once in a test", "Alert noise reviewed after one week"],
  "[3.4], [3.5]"),

# ---------------- Phase 4 ----------------
t("4.1", "Minecraft stack (itzg/minecraft-server)", ["area:games"],
  "First real game server, reachable by friends from the internet.",
  ["`stacks/games/minecraft/docker-compose.yml` with `itzg/minecraft-server`: `EULA=TRUE`, `TYPE` (paper or vanilla), `MEMORY`, `ENABLE_RCON` with password from sops, `VERSION` pinned",
   "Data on `/srv/data/minecraft`; `MemoryMax` via the [3.2] module",
   "Router: forward TCP 25565 to nuc; `networking.firewall.allowedTCPPorts = [25565]`",
   "Pre-backup hook: `rcon-cli save-off; save-all` then `save-on` after (wire into [3.5] pre/post)",
   "Optional: `itzg/mc-monitor` exporter for Grafana"],
  ["A friend connects from outside the LAN", "Backup includes a consistent world save", "Restart of the unit brings the server back with the same world"],
  "[3.2], [3.3], [3.5]"),
t("4.2", "Palworld stack (thijsvanloef/palworld-server-docker)", ["area:games"],
  "Palworld dedicated server with the leak-mitigating scheduled restart.",
  ["Compose stack with `thijsvanloef/palworld-server-docker`; `PLAYERS`, `SERVER_PASSWORD` and `ADMIN_PASSWORD` from sops, `RCON_ENABLED=true`",
   "Built-in `AUTO_REBOOT` cron at a quiet hour with `AUTO_REBOOT_WARN_MINUTES`; `BACKUP_ENABLED` to `/srv/data/palworld/backups`",
   "`MemoryMax` around 16 GB; note observed usage after a week",
   "Router: forward UDP 8211 (and 27015 if using the community list); firewall rule"],
  ["External connection succeeds", "Scheduled restart observed and players warned", "Memory stays under the cap for a week"],
  "[3.2], [3.3]"),
t("4.3", "Satisfactory stack (wolveix/satisfactory-server)", ["area:games"],
  "Satisfactory dedicated server.",
  ["Compose stack with `wolveix/satisfactory-server`; `MAXPLAYERS`, `AUTOSAVEINTERVAL`, `STEAMBETA=false`",
   "Data on `/srv/data/satisfactory`; `MemoryMax` around 16 GB (Satisfactory grows with factory size)",
   "Router: forward TCP and UDP 7777; firewall rule",
   "Claim the server from the in-game client and store the admin password in the password manager"],
  ["External connection succeeds", "Save survives a unit restart"],
  "[3.2], [3.3]"),
t("4.4", "Maintenance-window hooks: RCON broadcast before reboot, per-game backup hooks", ["area:games", "area:nix"],
  "Reboots and backups never surprise players.",
  ["Pre-reboot script called by the [2.3] timer: for each running game stack, RCON broadcast at T-5 min and T-1 min, then `docker compose stop` cleanly",
   "Per-game backup pre/post scripts registered with [3.5] (`backupPrepareCommand` / `backupCleanupCommand`)",
   "`docs/runbooks/game-ops.md`: how to broadcast, restart, restore a world from restic"],
  ["Triggering the reboot timer manually fires broadcasts in Minecraft and Palworld", "A restic restore of a world is performed once and documented"],
  "[2.3], [4.1], [4.2], [3.5]"),
t("4.5", "Resource policy: MemoryMax and CPUWeight per stack", ["area:containers", "area:games"],
  "Game servers keep their tick rate when an LLM job runs. With 96 GB the constraint is CPU, not RAM.",
  ["Set `resources` in each stack: games `CPUWeight=1000`, LLM `CPUWeight=200`, observability `CPUWeight=100`",
   "`MemoryMax` per stack summing to under about 80 GB, leaving headroom for page cache",
   "Consider `AllowedCPUs` to pin LLM to E-cores and games to P-cores; benchmark before committing",
   "Document the numbers in `docs/runbooks/data-layout.md` or a new `resources.md`"],
  ["`systemd-cgtop` shows the weights in effect", "Minecraft tick time stays under 50 ms while a 70B model generates"],
  "[4.1], [5.1]"),
t("4.6", "Template and runbook for adding a new game server", ["area:games", "area:docs"],
  "Adding the fourth game should take under an hour.",
  ["`stacks/games/_template/` with a compose file, env example, and README",
   "`docs/runbooks/new-game-server.md`: copy template, add ports to firewall and router, add to backup paths, add resource weights, add Grafana panel",
   "Try it on a fourth game (e.g. Valheim or Terraria) to validate"],
  ["A fourth server is up within one hour following only the runbook"],
  "[4.4], [4.5]"),

# ---------------- Phase 5 ----------------
t("5.1", "Ollama stack on CPU", ["area:llm"],
  "An OpenAI-compatible local LLM API using the 96 GB RAM pool. Intel GPU comes later ([5.4]).",
  ["`stacks/ai/docker-compose.yml` with `ollama/ollama`, models on `/srv/data/ollama`, bound to the Tailscale IP on 11434",
   "Env: `OLLAMA_NUM_PARALLEL=1`, `OLLAMA_MAX_LOADED_MODELS=1`, `OLLAMA_KEEP_ALIVE=30m`; threads left default then tuned (4P+8E+4LPE, try 12)",
   "Pull a small model (e.g. 8B Q4) and one large (70B Q4) and record tokens/s for each",
   "`MemoryMax` about 60 GB, low `CPUWeight` per [4.5]"],
  ["`curl http://nuc:11434/api/generate` over Tailscale returns text", "tokens/s recorded in `docs/llm-benchmarks.md` for two model sizes"],
  "[3.2], [3.3]"),
t("5.2", "Open WebUI behind Tailscale", ["area:llm"],
  "Chat UI for phone and laptop on the tailnet.",
  ["Add `ghcr.io/open-webui/open-webui` to the `ai` stack, `OLLAMA_BASE_URL` pointing at the ollama service, `WEBUI_SECRET_KEY` from sops",
   "Bind to the Tailscale IP only; enable auth, create the admin user on first login",
   "Data on `/srv/data/open-webui`, included in backups"],
  ["Chat works from the phone over Tailscale", "Unreachable from LAN and WAN"],
  "[5.1]"),
t("5.3", "Model storage budget and NVMe planning", ["area:llm", "area:backup"],
  "1 TB is shared between games, models and the Nix store. Decide what is allowed to grow.",
  ["Set a model quota (e.g. 200 GB) via a btrfs qgroup on the ollama subvolume or a Prometheus alert on directory size",
   "Exclude `/srv/data/ollama/models/blobs` from restic (re-pullable); include the manifests",
   "Document candidates for the second M.2 slot (2 TB NVMe for `/srv/data`) and the migration steps"],
  ["Alert fires when the quota is exceeded in a test", "Backup size drops after the exclusion"],
  "[5.1], [3.5], [3.6]"),
t("5.4", "Intel Xe3 iGPU acceleration trial (IPEX-LLM or llama.cpp SYCL/Vulkan)", ["area:llm", "stretch"],
  "Find out whether the Arc B390 iGPU beats CPU inference on this box. Known blocker: Level Zero init crashes on Panther Lake (intel/compute-runtime issues 918 and 920); check status first.",
  ["`hardware.graphics.enable` with `intel-compute-runtime`, `level-zero`, `intel-media-driver`; confirm `clinfo` and `sycl-ls` see the GPU",
   "Pass `/dev/dri` into a trial container: IPEX-LLM Ollama image, or upstream Ollama/llama.cpp built with SYCL or Vulkan",
   "Benchmark the same two models as [5.1]; record tokens/s, first-load compile time, and stability over an hour",
   "Go/no-go: promote to the `ai` stack or close with findings in `docs/llm-benchmarks.md`"],
  ["Benchmark table with CPU vs GPU numbers", "Decision recorded"],
  "[5.1]"),
t("5.5", "Intel NPU trial", ["area:llm", "stretch"],
  "Check whether the NPU is usable from NixOS for anything practical (OpenVINO, small models, Whisper).",
  ["Check `intel-npu-driver` and `openvino` availability in nixpkgs 26.05 and whether `/dev/accel/accel0` appears with the latest kernel",
   "Run one OpenVINO sample on the NPU if the stack loads",
   "Record go/no-go in `docs/llm-benchmarks.md`"],
  ["A one-paragraph finding, positive or negative"],
  "[5.4]"),

# ---------------- Phase 6 ----------------
t("6.1", "home-manager for the ops user", ["area:dev", "area:nix"],
  "A consistent shell on the server matching the workstation.",
  ["`home-manager` as a NixOS module for `ops`: zsh or bash, `starship`, `direnv`, `git` config, `tmux` (ported from the NAS repo), `eza`, `ripgrep`, `fd`, `htop`, `btop`",
   "Keep the same file usable on WSL via a `homeConfigurations` output (optional)"],
  ["Login shell on nuc has the expected prompt and aliases", "`home-manager` generation listed in `nixos-rebuild` output"],
  "[1.8]"),
t("6.2", "Dev shells: shopify, python, scripting", ["area:dev", "area:nix"],
  "Reproducible toolchains for Shopify admin scripting without polluting the host.",
  ["`dev/shopify.nix`: Node LTS, `@shopify/cli` (via `nodePackages` or an npm wrapper), `jq`, `graphql` tooling",
   "`dev/python.nix`: Python 3.13, `uv`, `ruff`",
   "`dev/scripting.nix`: `just`, `httpie`, `yq`",
   "Expose as `devShells.{shopify,python,scripting}`; `.envrc` examples in `dev/README.md`"],
  ["`nix develop .#shopify` on nuc gives a working `shopify version`", "Each shell enters in under 5 s once cached"],
  "[6.1]"),
t("6.3", "Shopify API tokens via sops in dev shells only", ["area:dev", "area:security"],
  "Tokens reach the shell environment from `/run/secrets`, never from the repo or a compose file.",
  ["`sops.secrets.shopify-admin-token` with `owner = ops`, mode 0400",
   "`shellHook` in the shopify dev shell exports `SHOPIFY_ADMIN_TOKEN=$(cat /run/secrets/shopify-admin-token)` when the file exists",
   "Add a pre-commit or CI grep for `shpat_` patterns as a safety net"],
  ["Token available inside the shell, absent from `git log -p`", "CI fails on a deliberately committed fake token"],
  "[6.2], [1.7]"),
t("6.4", "VS Code Remote-SSH over Tailscale and nix-ld", ["area:dev"],
  "Edit and run on the server from the workstation.",
  ["`programs.nix-ld.enable` so the VS Code server binary runs",
   "SSH config entry `Host nuc` via the Tailscale name in `~/.ssh/config` on the workstation",
   "Open the repo on nuc in VS Code, confirm the Nix and direnv extensions work"],
  ["Remote window opens, terminal has the dev shell via direnv"],
  "[6.2]"),
t("6.5", "Scheduled scripts as Nix-declared systemd timers", ["area:dev", "area:nix", "stretch"],
  "Run recurring Shopify jobs on the server with the same dev shell toolchain.",
  ["A `modules/services/jobs.nix` pattern: one systemd service plus timer per script, running as `ops`, env from sops",
   "Example: nightly hello job writing to `/srv/data/jobs/`; `OnFailure=` to the notifier"],
  ["Timer runs on schedule, output visible in `journalctl -u job-hello`"],
  "[6.3], [2.5]"),

# ---------------- Phase 7 ----------------
t("7.1", "Disaster recovery drill: reinstall from flake and restore from restic", ["area:backup", "area:install"],
  "Prove the whole system can be recreated from the repo and the NAS in under an hour.",
  ["Announce downtime; stop game stacks",
   "Either wipe and reinstall the NVMe, or install onto a second NVMe in the free slot, following `docs/runbooks/reinstall.md`",
   "`restic restore latest --target /srv/data` for all stacks",
   "Bring stacks up, verify worlds and Grafana history, time the whole thing"],
  ["Total time recorded, under 60 minutes", "Runbook corrections committed", "Players see their worlds intact"],
  "[1.8], [3.5], [4.x] complete"),
t("7.2", "Security review", ["area:security"],
  "Audit what is exposed and what runs as root.",
  ["Dump `nft list ruleset`; confirm only game ports are open on `eno1`",
   "Review `sshd -T`; Tailscale ACLs restrict SSH to the owner's devices",
   "Containers: run as non-root where the image supports it, `no-new-privileges`, read-only root fs where possible; Docker socket not mounted anywhere",
   "Revisit `wheelNeedsPassword = false` from [1.3]",
   "Record accepted risks in `docs/adr/0007-security-posture.md`"],
  ["Checklist complete, findings fixed or accepted in the ADR"],
  "[4.6], [5.2], [6.4]"),
t("7.3", "SMART, btrfs scrub, and thermal monitoring", ["area:observability"],
  "Catch disk and heat problems on a fanned mini PC running 24/7.",
  ["`services.smartd` with email or notifier hook; `smartctl` exporter or node-exporter textfile for Grafana",
   "`services.btrfs.autoScrub` monthly on the root pool",
   "Thermal: `lm_sensors`, CPU package temperature panel and alert above 90 C sustained"],
  ["Scrub timer listed in `systemctl list-timers`", "A SMART test alert delivered", "Temperature panel populated"],
  "[3.6]"),
t("7.4", "Secure Boot with lanzaboote", ["area:security", "stretch"],
  "Optional hardening once everything else is stable.",
  ["Follow the lanzaboote quick start: `sbctl create-keys`, enroll, switch bootloader to lanzaboote",
   "Update [1.1] BIOS notes and `docs/runbooks/reinstall.md` with the enrollment steps"],
  ["`bootctl status` shows Secure Boot enabled", "A reinstall still works following the runbook"],
  "[7.1]"),
t("7.5", "CV write-up", ["area:docs"],
  "A concise narrative of the system for a portfolio reader.",
  ["`docs/writeup.md`: problem, architecture, decisions (link ADRs), metrics (deploy latency, DR time, uptime), what went wrong and what was learned",
   "Link from README"],
  ["Reviewed by a second reader", "Numbers match runbook records"],
  "[7.1], [2.6]"),

# ---------------- Phase 8 ----------------
t("8.1", "ADR: K3s versus staying on compose", ["area:docs", "stretch"],
  "Decide with evidence, not enthusiasm.",
  ["`docs/adr/0008-k3s.md`: what K3s would add on one node, what it costs (RAM, complexity, learning), and the trigger conditions that would justify it (second node, need for rolling updates, portfolio value)"],
  ["ADR written with an explicit decision"],
  "[7.5]"),
t("8.2", "Single-node K3s alongside Docker with Flux pointed at this repo", ["area:containers", "stretch"],
  "Only if [8.1] says go.",
  ["`services.k3s` with `--docker` or containerd; decide whether it coexists with the Docker stacks",
   "Flux or Argo CD bootstrapped from a `k8s/` directory in this repo",
   "Resource reservation so K3s components stay under 2 GB"],
  ["`kubectl get nodes` Ready", "Flux reconciles a hello deployment from the repo"],
  "[8.1]"),
t("8.3", "Migrate the observability stack to Helm", ["area:containers", "area:observability", "stretch"],
  "Lowest-risk stack to move first.",
  ["kube-prometheus-stack via Helm through Flux; keep node-exporter as the NixOS service",
   "Compare: lines of config, upgrade steps, memory, time to change a dashboard"],
  ["Comparison table in the ADR"],
  "[8.2]"),
t("8.4", "Decide: migrate games and LLM, or stop", ["area:docs", "stretch"],
  "Close the loop.",
  ["Update ADR 0008 with the outcome of [8.3] and the decision for the remaining stacks"],
  ["Decision recorded; either a migration plan or K3s removed"],
  "[8.3]"),
]
